name: Mise à jour quotidienne de l'Excel

on:
  schedule:
    - cron: '0 8 * * *'  # tous les jours à 8h UTC
  workflow_dispatch:       # permet aussi de lancer manuellement

jobs:
  update-excel:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer les fichiers
      uses: actions/checkout@v4

    - name: Installer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Installer les dépendances
      run: pip install -r requirements.txt

    - name: Exécuter le script
      run: python script_csv_to_excel.py

    - name: Sauvegarder l'Excel mis à jour
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'Automated Bot'
        git config --global user.email 'bot@github.com'
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        git add Base de donnees a mettre a jour.xlsx
        git commit -m "Mise à jour automatique" || echo "Rien à commiter"
        git push
